In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
df = pd.read_csv(r'C:\Users\PL\Documents\ML data\diamonds.csv')

In [5]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object
 3   color       53940 non-null  object
 4   clarity     53940 non-null  object
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB

In [7]:
X = df[[
       'carat',
       'cut',
       'color',
       'clarity',
       'depth',
       'table',
       'x',
       'y',
       'z']]
y = df['price']

X = pd.get_dummies(
    X,columns=['cut','color','clarity'],
    drop_first=True)

In [8]:
X.isna().sum()

carat            0
depth            0
table            0
x                0
y                0
z                0
cut_Good         0
cut_Ideal        0
cut_Premium      0
cut_Very Good    0
color_E          0
color_F          0
color_G          0
color_H          0
color_I          0
color_J          0
clarity_IF       0
clarity_SI1      0
clarity_SI2      0
clarity_VS1      0
clarity_VS2      0
clarity_VVS1     0
clarity_VVS2     0
dtype: int64

In [9]:
X_train, X_test, y_train, y_test = train_test_split (
    X, y, test_size = 0.25, random_state = 42 )

In [10]:
model = LinearRegression()

model.fit(X_train, y_train)
preds = model.predict(X_test)

In [11]:
mse = mean_squared_error(y_test, preds)
rmse = mse**0.5
r2 = r2_score(y_test, preds)

In [12]:
print(rmse)
print(r2)

1124.086094584751
0.9195675153810777

In [13]:
df['clarity'].unique()

array(['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF'],
      dtype=object)

In [14]:
coeffs = pd.Series(model.coef_,index=X.columns)
coeffs.sort_values(ascending = False)

carat            11225.952724
clarity_IF        5425.243563
clarity_VVS1      5074.608126
clarity_VVS2      5004.660604
clarity_VS1       4629.936027
clarity_VS2       4316.145626
clarity_SI1       3729.148752
clarity_SI2       2756.212354
cut_Ideal          849.166092
cut_Premium        775.214302
cut_Very Good      743.626442
cut_Good           584.196702
y                   -4.215825
table              -26.681136
z                  -34.744938
depth              -64.541578
color_E           -220.295026
color_F           -279.519762
color_G           -497.513854
x                 -987.068148
color_H           -993.777689
color_I          -1481.776975
color_J          -2382.015227
dtype: float64

In [15]:
print(model.intercept_)

2111.9171095439456

In [16]:
print(X_test.iloc[1].sort_values(ascending=False))

depth             60.0
table             57.0
x                 5.44
y                 5.42
z                 3.26
color_F           True
cut_Very Good     True
clarity_VVS2      True
carat             0.58
cut_Premium      False
cut_Ideal        False
color_E          False
cut_Good         False
color_G          False
color_H          False
color_I          False
color_J          False
clarity_IF       False
clarity_SI1      False
clarity_SI2      False
clarity_VS1      False
clarity_VS2      False
clarity_VVS1     False
Name: 50052, dtype: object

In [45]:
print(model.predict(X_test.iloc[[1]]))

[3185.37244563]

In [21]:
df_results = pd.DataFrame({
    'actual': y_test,
    'predicted': preds,
    'error': y_test - preds})

In [26]:
df_results = df_results.reindex(df_results['error'].abs().sort_values(ascending=False).index)
df_results.head(10)

       actual     predicted         error
25998   15223  30591.012205 -15368.012205
26444   15984  30502.891697 -14518.891697
25999   15223  29683.971014 -14460.971014
24328   12587  25908.954850 -13321.954850
21862    9925  21531.010937 -11606.010937
27679   18701  28831.131562 -10130.131562
27196   17499   8529.772810   8969.227190
26407   15928   7272.970373   8655.029627
26491   16087   7637.074738   8449.925262
27673   18691  10619.700245   8071.299755